Repository dipdup-io/celestia-indexer, pull requests merged in 2023-09, with the labels that each got.

#42 Add validator table
  internal/storage/generic.go
  internal/storage/message.go
  internal/storage/mock/validator.go
  internal/storage/postgres/core.go
  internal/storage/postgres/stats_test.go
  internal/storage/postgres/storage_test.go
  internal/storage/postgres/transaction.go
  internal/storage/postgres/transaction_test.go
  internal/storage/postgres/validator.go
  internal/storage/validator.go
  pkg/indexer/rollback/rollback.go
  pkg/indexer/storage/storage.go
  test/data/message.yml
  test/data/tx.yml
  test/data/validator.yml
Labels: enhancement

#43 Refactoring: address and balance entities
  cmd/api/handler/address.go
  cmd/api/handler/address_test.go
  cmd/api/handler/responses/address.go
  cmd/api/handler/responses/decoding.go
  cmd/api/handler/search.go
  cmd/api/handler/search_test.go
  cmd/api/handler/validators.go
  internal/storage/address.go
  internal/storage/balance.go
  internal/storage/generic.go
  internal/storage/mock/address.go
  internal/storage/mock/balance.go
  internal/storage/postgres/address.go
  internal/storage/postgres/storage_test.go
  internal/storage/postgres/transaction.go
  internal/storage/postgres/transaction_test.go
  internal/storage/tx.go
  pkg/indexer/decode/message.go
  pkg/indexer/decode/message_test.go
  pkg/indexer/genesis/genesis_test.go
  pkg/indexer/genesis/parse.go
  pkg/indexer/genesis/save.go
  pkg/indexer/storage/storage.go
  pkg/node/types/genesis.go
  pkg/types/address.go
  pkg/types/address_test.go
  test/data/address.yml
  test/data/balance.yml
  test/json/genesis.json
Labels: refactoring

#45 enables stopper
  .gitignore
  cmd/indexer/main.go
  pkg/indexer/genesis/genesis.go
  pkg/indexer/indexer.go
  pkg/indexer/parser/parse.go
  pkg/indexer/parser/parser.go
  pkg/indexer/receiver/receiver.go
  pkg/indexer/rollback/rollback.go
  pkg/indexer/storage/storage.go
  pkg/stopper/stopper.go
Labels: enhancement

#44 Add MsgRegisterEvmAddress and MsgWithdrawAddress
  .github/workflows/test.yml
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  go.mod
  go.sum
  internal/storage/types/msg_type.go
  internal/storage/types/msg_type_bitmask.go
  internal/storage/types/msg_type_bitmask_test.go
  internal/storage/types/msg_type_enum.go
  internal/storage/types/tx_address_type.go
  internal/storage/types/tx_address_type_enum.go
  pkg/indexer/decode/message.go
  pkg/indexer/decode/message_test.go
Labels: enhancement

#46 Add network constants
  Makefile
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/constant.go
  cmd/api/handler/responses/constants.go
  cmd/api/init.go
  internal/storage/constant.go
  internal/storage/denom_metadata.go
  internal/storage/generic.go
  internal/storage/mock/constant.go
  internal/storage/mock/denom_metadata.go
  internal/storage/postgres/constant.go
  internal/storage/postgres/core.go
  internal/storage/postgres/custom_types.go
  internal/storage/postgres/denom_metadata.go
  internal/storage/postgres/storage_test.go
  internal/storage/postgres/transaction.go
  internal/storage/types/module.go
  internal/storage/types/module_enum.go
  pkg/indexer/genesis/constant.go
  pkg/indexer/genesis/denom_metadata.go
  pkg/indexer/genesis/parse.go
  pkg/indexer/genesis/save.go
  pkg/node/types/genesis.go
  test/data/constant.yml
  test/data/denom_metadata.yml
Labels: enhancement

#47 Fix: join stats for blocks API
  cmd/api/handler/block.go
Labels: bug

#48 Fix: block notifications
  cmd/api/handler/websocket/channel.go
  pkg/indexer/storage/storage.go
Labels: bug

#49 Fix: add search endpoint
  cmd/api/init.go
Labels: bug

#50 Fix: saving addresses and relations with tx
  cmd/api/handler/namespace.go
  cmd/indexer/main.go
  internal/storage/address.go
  internal/storage/generic.go
  internal/storage/message.go
  internal/storage/message_address.go
  internal/storage/postgres/core.go
  internal/storage/postgres/custom_types.go
  internal/storage/postgres/index.go
  internal/storage/postgres/transaction.go
  internal/storage/postgres/transaction_test.go
  internal/storage/postgres/tx.go
  internal/storage/signers.go
  internal/storage/tx.go
  internal/storage/tx_address.go
  internal/storage/types/msg_address_type.go
  internal/storage/types/msg_address_type_enum.go
  internal/storage/types/tx_address_type_enum.go
  pkg/indexer/decode/message.go
  pkg/indexer/decode/message_test.go
  pkg/indexer/decode/tx.go
  pkg/indexer/genesis/parse.go
  pkg/indexer/genesis/save.go
  pkg/indexer/indexer.go
  pkg/indexer/parser/parseTxs.go
  pkg/indexer/receiver/worker.go
  pkg/indexer/rollback/balances.go
  pkg/indexer/rollback/message.go
  pkg/indexer/rollback/namespace.go
  pkg/indexer/rollback/rollback.go
  pkg/indexer/rollback/total_supply.go
  pkg/indexer/rollback/tx.go
  pkg/indexer/storage/address.go
  pkg/indexer/storage/message.go
  pkg/indexer/storage/namespace.go
  pkg/indexer/storage/storage.go
  pkg/types/block.go
  test/data/msg_address.yml
  test/data/signer.yml
Labels: bug

#51 adds license check action
  .github/workflows/license-check.yml
  Makefile
  init.dev.sh
Labels: enhancement

#52 updates actions
  .github/workflows/build.yml
  .github/workflows/license-check.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  go.mod
  go.sum
  init.dev.sh
Labels: enhancement

#53 adds set_withdraw_address event type
  internal/storage/types/event_type.go
  pkg/indexer/storage/storage.go
Labels: enhancement

#56 Add pyroscope
  build/dipdup.yml
  cmd/api/config.go
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/init.go
  cmd/api/main.go
  cmd/indexer/init.go
  cmd/indexer/main.go
  go.mod
  go.sum
  internal/profiler/profiler.go
  pkg/indexer/config/config.go
Labels: enhancement

#55 Fix: websocket API
  Makefile
  cmd/api/handler/websocket/channel.go
  cmd/api/handler/websocket/channel_test.go
  cmd/api/handler/websocket/client.go
  cmd/api/handler/websocket/filters.go
  cmd/api/handler/websocket/filters_test.go
  cmd/api/handler/websocket/manager.go
  cmd/api/handler/websocket/messages.go
  cmd/api/handler/websocket/processors.go
  cmd/api/init.go
  test/newman/env.json
  test/newman/tests.json
Labels: bug

#57 Fix: test workflow
  .github/workflows/test.yml
Labels: bug

#58 refactors basemodule
  cmd/api/handler/websocket/channel.go
  cmd/api/handler/websocket/manager.go
  cmd/api/handler/websocket/map.go
  cmd/indexer/main.go
  go.mod
  go.sum
  pkg/indexer/genesis/genesis.go
  pkg/indexer/genesis/save.go
  pkg/indexer/indexer.go
  pkg/indexer/parser/listen.go
  pkg/indexer/parser/parse.go
  pkg/indexer/parser/parser.go
  pkg/indexer/receiver/genesis.go
  pkg/indexer/receiver/receiver.go
  pkg/indexer/receiver/sequencer.go
  pkg/indexer/receiver/sync.go
  pkg/indexer/receiver/worker.go
  pkg/indexer/rollback/rollback.go
  pkg/indexer/storage/storage.go
  pkg/indexer/storage/storage_test.go
  pkg/stopper/stopper.go
Labels: refactoring

#59 Fix: create decoder once
  pkg/indexer/decode/tx.go
  pkg/indexer/receiver/receiver.go
  pkg/indexer/storage/storage.go
Labels: bug

#63 Feature: add new endpoints
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/block.go
  cmd/api/handler/block_test.go
  cmd/api/handler/namespace.go
  cmd/api/handler/namespace_test.go
  cmd/api/handler/requests.go
  cmd/api/handler/responses/namespace_message.go
  cmd/api/handler/stats.go
  cmd/api/init.go
  internal/storage/mock/constant.go
  internal/storage/mock/namespace.go
  internal/storage/namespace.go
  internal/storage/postgres/core.go
  internal/storage/postgres/namespace.go
  internal/storage/postgres/storage_test.go
  internal/storage/types/event_type_enum.go
Labels: enhancement

#60 adds unit test for parser module.
  pkg/indexer/decode/tx.go
  pkg/indexer/parser/listen.go
  pkg/indexer/parser/parse.go
  pkg/indexer/parser/parser_test.go
  pkg/indexer/receiver/receiver.go
  pkg/indexer/receiver/sequencer.go
  pkg/indexer/receiver/worker.go
Labels: enhancement

#66 Fix: add total supply to head API
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/responses/state.go
Labels: bug

#67 Compute total accounts
  .github/workflows/test.yml
  internal/storage/postgres/transaction.go
  internal/storage/postgres/transaction_test.go
  pkg/indexer/genesis/save.go
  pkg/indexer/storage/address.go
  pkg/indexer/storage/storage.go
Labels: enhancement

#65 Feature: add balance computing
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/address_test.go
  cmd/api/handler/responses/address.go
  cmd/api/handler/search_test.go
  internal/storage/address.go
  internal/storage/balance.go
  internal/storage/block.go
  internal/storage/postgres/transaction.go
  internal/storage/postgres/transaction_test.go
  internal/test_suite/helpers.go
  pkg/indexer/decode/event.go
  pkg/indexer/decode/event_test.go
  pkg/indexer/decode/map.go
  pkg/indexer/decode/map_test.go
  pkg/indexer/decode/message.go
  pkg/indexer/decode/message_test.go
  pkg/indexer/genesis/genesis_test.go
  pkg/indexer/genesis/parse.go
  pkg/indexer/parser/balance.go
  pkg/indexer/parser/begin_block_events.go
  pkg/indexer/parser/events_result.go
  pkg/indexer/parser/parse.go
  pkg/indexer/parser/parseTxs.go
  pkg/indexer/parser/parser_test.go
  pkg/indexer/rollback/balances.go
  pkg/indexer/rollback/rollback.go
  pkg/indexer/storage/storage.go
  test/data/balance.yml
  test/data/rollback/balance.yml
Labels: enhancement

#68 Fix: don't create validator from failed tx
  pkg/indexer/decode/message.go
  pkg/indexer/decode/message_test.go
  pkg/indexer/genesis/parse.go
  pkg/indexer/parser/parseTxs.go
Labels: bug

#71 Fix: tx API filters
  cmd/api/handler/tx.go
Labels: bug

#69 Fix: computing namespace hash
  cmd/api/handler/namespace.go
  cmd/api/handler/namespace_test.go
  cmd/api/handler/responses/namespace.go
  cmd/api/handler/search.go
  internal/storage/namespace.go
  internal/storage/namespace_test.go
  pkg/indexer/rollback/namespace.go
Labels: bug

#70 Fix: don't skip namespace in another message but in the same tx
  cmd/indexer/main.go
  pkg/indexer/storage/message.go
Labels: bug

#75 Fix: nil coin events
  internal/storage/balance.go
  pkg/indexer/parser/balance.go
  pkg/indexer/parser/balance_test.go
Labels: bug

#72 Fix: add tx API list test
  cmd/api/handler/tx_test.go
Labels: bug

#73 Fix: join balance in list endpoint of address API
  cmd/api/handler/address.go
  cmd/api/handler/address_test.go
  cmd/api/handler/requests.go
  internal/storage/address.go
  internal/storage/mock/address.go
  internal/storage/postgres/address.go
  internal/storage/postgres/scopes.go
  internal/storage/postgres/storage_test.go
Labels: bug

#74 Fix: total blobs size
  pkg/indexer/storage/storage.go
Labels: bug

#76 adds events msgs
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  internal/storage/balance.go
  internal/storage/types/event_type.go
  internal/storage/types/event_type_enum.go
  internal/storage/types/msg_address_type.go
  internal/storage/types/msg_address_type_enum.go
  internal/storage/types/msg_type.go
  internal/storage/types/msg_type_enum.go
  pkg/indexer/decode/handle/authz.go
  pkg/indexer/decode/handle/bank.go
  pkg/indexer/decode/handle/blob.go
  pkg/indexer/decode/handle/createAddresses.go
  pkg/indexer/decode/handle/createAddresses_test.go
  pkg/indexer/decode/handle/distribution.go
  pkg/indexer/decode/handle/feegrant.go
  pkg/indexer/decode/handle/gov.go
  pkg/indexer/decode/handle/qgb.go
  pkg/indexer/decode/handle/slashing.go
  pkg/indexer/decode/handle/staking.go
  pkg/indexer/decode/handle/test/authz_test.go
  pkg/indexer/decode/handle/test/bank_test.go
  pkg/indexer/decode/handle/test/blob_test.go
  pkg/indexer/decode/handle/test/distribution_test.go
  pkg/indexer/decode/handle/test/feegrant_test.go
  pkg/indexer/decode/handle/test/gov_test.go
  pkg/indexer/decode/handle/test/qgb_test.go
  pkg/indexer/decode/handle/test/slashing_test.go
  pkg/indexer/decode/handle/test/staking_test.go
  pkg/indexer/decode/handle/test/vesting_test.go
  pkg/indexer/decode/handle/vesting.go
  pkg/indexer/decode/message.go
  pkg/indexer/decode/message_test.go
Labels: enhancement, refactoring

#80 Fix: received coins
  pkg/indexer/parser/balance.go
Labels: bug

#82 Feature: add block time in stats
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/block_test.go
  cmd/api/handler/responses/block.go
  internal/storage/block_stats.go
  pkg/indexer/storage/storage.go
  test/data/block_stats.yml
  test/data/rollback/block_stats.yml
Labels: enhancement

#83 Add active namespace endpoint
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/namespace.go
  cmd/api/handler/namespace_test.go
  cmd/api/handler/responses/namespace.go
  cmd/api/init.go
  internal/storage/mock/namespace.go
  internal/storage/namespace.go
  internal/storage/postgres/namespace.go
  internal/storage/postgres/storage_test.go
  internal/storage/postgres/transaction_test.go
  test/data/namespace_message.yml
Labels: enhancement

#84 Added total namespaces calculation.
  internal/storage/address.go
  internal/storage/postgres/transaction.go
  internal/storage/postgres/transaction_test.go
  pkg/indexer/genesis/save.go
  pkg/indexer/rollback/namespace.go
  pkg/indexer/storage/namespace.go
  pkg/indexer/storage/storage.go
Labels: bug

#85 Add get blob endpoint
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/namespace.go
  cmd/api/handler/namespace_test.go
  cmd/api/init.go
  pkg/node/api.go
  pkg/node/mock/api.go
Labels: enhancement

#86 Test: storage module
  internal/storage/generic.go
  internal/storage/mock/generic.go
  internal/storage/postgres/transaction.go
  pkg/indexer/indexer.go
  pkg/indexer/rollback/balances.go
  pkg/indexer/rollback/message.go
  pkg/indexer/rollback/namespace.go
  pkg/indexer/rollback/tx.go
  pkg/indexer/storage/address.go
  pkg/indexer/storage/address_test.go
  pkg/indexer/storage/functions.go
  pkg/indexer/storage/functions_test.go
  pkg/indexer/storage/message.go
  pkg/indexer/storage/message_test.go
  pkg/indexer/storage/namespace.go
  pkg/indexer/storage/namespace_test.go
  pkg/indexer/storage/state.go
  pkg/indexer/storage/state_test.go
  pkg/indexer/storage/storage.go
  pkg/indexer/storage/storage_test.go
Labels: refactoring

#87 Fix: refactoring blocks request
  internal/storage/postgres/block.go
  internal/storage/postgres/storage_test.go
Labels: bug

#89 Fix: memory leak
  pkg/indexer/parser/parser_test.go
  pkg/indexer/rollback/rollback_test.go
  pkg/node/rpc/api.go
  pkg/types/block.go
  pkg/types/block_results.go
  pkg/types/hex.go
  pkg/types/hex_test.go
Labels: bug

#88 Add separate datasource for blob receiving
  .env.example
  build/dipdup.yml
Labels: enhancement

#90 CLS 27 clean up block data
  pkg/indexer/parser/parser_test.go
  pkg/types/block.go
Labels: refactoring

#92 Fix: memory leak
  pkg/indexer/receiver/readBlocks.go
  pkg/indexer/receiver/receiver.go
  pkg/indexer/receiver/worker.go
Labels: bug

#91 Add newman tests for API
  test/newman/tests.json
Labels: enhancement

#94 Feature: add endpoint with count of affected namespaces in block
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/block.go
  cmd/api/handler/block_test.go
  cmd/api/init.go
  internal/storage/mock/namespace.go
  internal/storage/namespace.go
  internal/storage/postgres/namespace.go
  internal/storage/postgres/storage_test.go
Labels: enhancement

#95 Tests: rollback balances
  internal/consts/currency.go
  pkg/indexer/parser/balance.go
  pkg/indexer/parser/balance_test.go
  pkg/indexer/rollback/balances.go
  pkg/indexer/rollback/balances_test.go
Labels: refactoring

#96 adds test for NewCoinReceived.
  pkg/indexer/decode/event_test.go
Labels: enhancement

#98 CLS-36 adds bank messages
  internal/storage/types/msg_address_type.go
  internal/storage/types/msg_address_type_enum.go
  internal/storage/types/msg_type.go
  internal/storage/types/msg_type_enum.go
  pkg/indexer/decode/handle/bank.go
  pkg/indexer/decode/handle/createAddresses.go
  pkg/indexer/decode/handle/test/bank_test.go
  pkg/indexer/decode/message.go
Labels: enhancement

#99 CLS 37 add authz module messages
  internal/storage/types/msg_type.go
  internal/storage/types/msg_type_enum.go
  pkg/indexer/decode/handle/authz.go
  pkg/indexer/decode/handle/test/authz_test.go
  pkg/indexer/decode/message.go
Labels: enhancement

#101 Fix: live-indexing
  pkg/indexer/receiver/readBlocks.go
  pkg/indexer/receiver/sequencer.go
Labels: bug

#100 CLS 38 add distribution module messages
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  internal/storage/types/msg_address_type.go
  internal/storage/types/msg_address_type_enum.go
  internal/storage/types/msg_type.go
  internal/storage/types/msg_type_enum.go
  pkg/indexer/decode/handle/blob.go
  pkg/indexer/decode/handle/createAddresses_test.go
  pkg/indexer/decode/handle/distribution.go
  pkg/indexer/decode/handle/qgb.go
  pkg/indexer/decode/handle/slashing.go
  pkg/indexer/decode/handle/staking.go
  pkg/indexer/decode/handle/test/distribution_test.go
  pkg/indexer/decode/handle/test/qgb_test.go
  pkg/indexer/decode/handle/test/slashing_test.go
  pkg/indexer/decode/handle/test/staking_test.go
  pkg/indexer/decode/message.go
  pkg/indexer/storage/message_test.go
Labels: enhancement

#102 Refactoring: profiler config
  build/dipdup.yml
  docs/balance-computing.md
  internal/profiler/profiler.go
Labels: refactoring

#103 Add endpoint with genesis transactions
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/tx.go
  cmd/api/handler/tx_test.go
  cmd/api/init.go
  internal/storage/mock/tx.go
  internal/storage/postgres/stats_test.go
  internal/storage/postgres/storage_test.go
  internal/storage/postgres/transaction_test.go
  internal/storage/postgres/tx.go
  internal/storage/tx.go
  test/data/namespace_message.yml
  test/data/tx.yml
Labels: enhancement

#108 Fixed bug with sequencer starting from wrong index.
  build/dipdup.yml
  pkg/indexer/receiver/sequencer.go
Labels: bug

#109 Refactoring: websocket channels without clients
  cmd/api/handler/websocket/channel.go
Labels: refactoring

#106 adds MsgCancelUnbondingDelegation support.
  internal/storage/types/msg_address_type.go
  internal/storage/types/msg_address_type_enum.go
  internal/storage/types/msg_type.go
  internal/storage/types/msg_type_enum.go
  pkg/indexer/decode/handle/staking.go
  pkg/indexer/decode/handle/test/staking_test.go
  pkg/indexer/decode/message.go
Labels: enhancement

#112 Add messages to get transactions endpoint
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  cmd/api/handler/requests.go
  cmd/api/handler/responses/tx.go
  cmd/api/handler/tx.go
  cmd/api/handler/tx_test.go
  internal/storage/postgres/scopes.go
  internal/storage/postgres/storage_test.go
  internal/storage/tx.go
Labels: enhancement

#111 adds msgs type bitmasks
  internal/storage/postgres/storage_test.go
  internal/storage/types/msg_type.go
  internal/storage/types/msg_type_bitmask.go
  internal/storage/types/msg_type_bitmask_test.go
  test/data/tx.yml
Labels: enhancement

#113 Refactoring: saving a lot of events via CopyFrom
  internal/storage/event.go
  internal/storage/generic.go
  internal/storage/mock/generic.go
  internal/storage/postgres/transaction.go
  internal/storage/postgres/transaction_test.go
  pkg/indexer/storage/storage.go
  pkg/node/types/genesis.go
Labels: enhancement, refactoring

#116 Fix: websocket going away error
  cmd/api/handler/websocket/client.go
Labels: bug

#117 CLS 64 fix stats on block by websocket
  cmd/api/handler/websocket/errors.go
  cmd/api/handler/websocket/filters.go
  cmd/api/handler/websocket/processors.go
  cmd/api/handler/ws_test.go
  internal/storage/block.go
  internal/storage/mock/block.go
  internal/storage/postgres/block.go
  internal/storage/postgres/storage_test.go
Labels: enhancement

#120 CLS 67 fix bug with parsing tx 0 in block 151599
  cmd/api/handler/block.go
  go.mod
  go.sum
  pkg/indexer/decode/tx.go
  pkg/indexer/decode/tx_test.go
Labels: bug

#121 Fix: websocket abnormal closure
  cmd/api/handler/websocket/client.go
  cmd/api/handler/websocket/manager.go
Labels: bug
