Repository dipdup-io/celestia-indexer, pull requests merged in 2023-10, with the labels that each got.

#122 handle websocket errors
  cmd/api/handler/websocket/client.go
  cmd/api/handler/websocket/errors.go
Labels: bug

#124 Fix: total namespace calculation
  internal/storage/postgres/transaction.go
  internal/storage/postgres/transaction_test.go
Labels: bug

#125 CLS 79 add coverage badge
  .github/workflows/license.yml
  .github/workflows/test.yml
  README.md
Labels: enhancement

#126 Fix: security issue #4
  go.mod
  go.sum
Labels: bug

#129 added support for tia token while decoding tx
  internal/consts/currency.go
  pkg/indexer/decode/tx.go
  pkg/indexer/decode/tx_test.go
Labels: enhancement

#130 CLS 87 update node to rc 15
  go.mod
  go.sum
Labels: enhancement

#131 rename license header to fix github identification
  HEADER
  Makefile
Labels: refactoring

#132 CLS 88 add support of ibc transfer messages
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  internal/storage/types/msg_address_type.go
  internal/storage/types/msg_address_type_enum.go
  internal/storage/types/msg_type.go
  internal/storage/types/msg_type_enum.go
  pkg/indexer/decode/handle/ibc.go
  pkg/indexer/decode/handle/test/ibc_test.go
  pkg/indexer/decode/message.go
Labels: enhancement

#133 CLS 92 add ibc events
  cmd/api/docs/docs.go
  cmd/api/docs/swagger.json
  cmd/api/docs/swagger.yaml
  internal/storage/types/event_type.go
  internal/storage/types/event_type_enum.go
Labels: bug

#134 disabled parsing of receiver address in IBC Transfer
  .run/Indexer.run.xml
  pkg/indexer/decode/handle/ibc.go
  pkg/indexer/decode/handle/test/ibc_test.go
Labels: bug
